export class User{
    userId:number;
    userphoto:File;
      name:string;
      contactNumber:number;
      fatherName:string;
      fatherphoneNumber:number;
      motherName:string;
      motherphoneNumber:number;      
      dob:string;
      bloodGroup:string;
      emergencyContactNumber:number;
      nameOfTheEmployer:string;
      officeAddress:string;
      telephoneNumber:number;
      emailId:string;
      permanentAddress:string;
      idProof:string;
 }